export default defineNuxtConfig({
  ssr: true,
  devtools: { enabled: false },
  css: ['~/assets/css/aurora.css', '~/assets/css/aurora-v9.css'],
  modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt'],
  app: {
    baseURL: '/makon/',
    head: {
      title: 'MAKON — Ko\'chmas mulk platformasi',
      htmlAttrs: { lang: 'uz' },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover' },
        { name: 'description', content: 'MAKON — Toshkentdagi premium biznes markazlari, ofislar va ombor maydonlari uchun yagona boshqaruv platformasi.' },
        { name: 'theme-color', content: '#2563eb' },
        { name: 'color-scheme', content: 'light' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'default' },
        { name: 'mobile-web-app-capable', content: 'yes' },
        { property: 'og:title', content: 'MAKON — Ko\'chmas mulk platformasi' },
        { property: 'og:description', content: 'Tashkent City, Trillant Tower, IT Park va boshqa premium binolarda ofis, savdo va ombor maydonlari.' },
        { property: 'og:type', content: 'website' },
      ],
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Sora:wght@600;700;800&display=swap' },
        { rel: 'icon', type: 'image/svg+xml', href: '/makon/favicon.svg' },
        { rel: 'stylesheet', href: 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css' },
      ],
      script: [],
    },
  },
  runtimeConfig: {
    public: {
      apiBase: 'https://api.makon.uz/v1',
    },
  },
  nitro: {
    prerender: {
      crawlLinks: true,
      routes: [
        '/', '/catalog', '/login', '/register', '/register/eri',
        '/auth/register', '/auth/verify',
        '/200.html', '/404.html',
        '/dashboard', '/dashboard/executive', '/dashboard/building',
        '/profile', '/notifications', '/reports',
        '/management/buildings', '/management/units', '/management/listings',
        '/management/applications', '/management/contracts', '/management/tenants',
        '/management/service-requests', '/management/floor-plans', '/management/visual-settings',
        '/contracts', '/applications/new',
        '/finance/periods', '/finance/invoices', '/finance/debts', '/finance/approvals',
        '/finance/inventory', '/finance/stock-issues',
        '/facility/work-orders', '/facility/material-requests',
        '/meters', '/meters/readings',
        '/admin/users', '/admin/roles', '/admin/settings',
        '/admin/audit', '/admin/backups', '/admin/monitoring',
        '/admin/notification-templates', '/admin/login-history',
        '/didox/signatures', '/eri/signatures',
        '/cabinet', '/cabinet/units', '/cabinet/applications', '/cabinet/contracts',
        '/cabinet/services', '/cabinet/service-requests', '/cabinet/meter-readings',
      ],
      failOnError: false,
    },
  },
  typescript: { strict: false },
})
