// stores/service.ts
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import type {
  ServiceRequest,
  WorkOrder,
  MaterialRequest,
  WarehouseItem,
  WarehouseTransaction,
  Supplier,
  Meter,
  MeterReading,
} from '~/types'

export const useServiceStore = defineStore('service', () => {
  const serviceRequests = ref<ServiceRequest[]>([])
  const workOrders = ref<WorkOrder[]>([])
  const materialRequests = ref<MaterialRequest[]>([])
  const warehouseItems = ref<WarehouseItem[]>([])
  const warehouseTransactions = ref<WarehouseTransaction[]>([])
  const suppliers = ref<Supplier[]>([])
  const meters = ref<Meter[]>([])
  const meterReadings = ref<MeterReading[]>([])
  const initialized = ref(false)

  function initMockData() {
    if (initialized.value) return
    initialized.value = true

    serviceRequests.value = [
      {
        id: 'sr1',
        number: 'SR-2025-005',
        buildingId: 'b2',
        unitId: 'un2',
        category: 'Santexnika',
        description: 'Kran oqib yopti',
        priority: 'HIGH',
        status: 'IN_PROGRESS',
        createdBy: 'u1',
        assignedTo: 'w1',
        workOrderId: 'wo1',
        createdAt: '2025-06-02T10:00:00',
        updatedAt: '2025-06-03T09:00:00',
      },
      {
        id: 'sr2',
        number: 'SR-2025-006',
        buildingId: 'b1',
        unitId: 'un1',
        category: 'Elektr',
        description: 'Rozetka ishlamayapti',
        priority: 'MEDIUM',
        status: 'ASSIGNED',
        createdBy: 'u1',
        assignedTo: 'w2',
        workOrderId: 'wo2',
        createdAt: '2025-06-04T14:00:00',
        updatedAt: '2025-06-04T14:30:00',
      },
      {
        id: 'sr3',
        number: 'SR-2025-007',
        buildingId: 'b4',
        unitId: null,
        category: 'Tozalash',
        description: 'Lift toza emas',
        priority: 'LOW',
        status: 'CREATED',
        createdBy: 'u1',
        assignedTo: null,
        workOrderId: null,
        createdAt: '2025-06-05T08:00:00',
        updatedAt: '2025-06-05T08:00:00',
      },
      {
        id: 'sr4',
        number: 'SR-2025-008',
        buildingId: 'b3',
        unitId: 'un4',
        category: 'HVAC',
        description: 'Konditsioner sovutmayapti',
        priority: 'URGENT',
        status: 'DONE',
        createdBy: 'u1',
        assignedTo: 'w1',
        workOrderId: 'wo3',
        createdAt: '2025-05-28T09:00:00',
        updatedAt: '2025-05-30T16:00:00',
      },
      {
        id: 'sr5',
        number: 'SR-2025-009',
        buildingId: 'b1',
        unitId: 'un5',
        category: 'Devor',
        description: 'Devorda yorilish',
        priority: 'MEDIUM',
        status: 'APPROVED',
        createdBy: 'u1',
        assignedTo: 'w2',
        workOrderId: null,
        createdAt: '2025-06-06T11:00:00',
        updatedAt: '2025-06-06T12:00:00',
      },
    ]

    workOrders.value = [
      {
        id: 'wo1',
        number: 'WO-2025-003',
        serviceRequestId: 'sr1',
        buildingId: 'b2',
        unitId: 'un2',
        contractorId: 'sup1',
        description: 'Kran almashtirish',
        estimatedCost: 850000,
        actualCost: 780000,
        status: 'IN_PROGRESS',
        scheduledDate: '2025-06-03T10:00:00',
        completedAt: null,
        inspectionNotes: '',
        photos: [],
        createdAt: '2025-06-02T11:00:00',
        updatedAt: '2025-06-03T09:00:00',
      },
      {
        id: 'wo2',
        number: 'WO-2025-004',
        serviceRequestId: 'sr2',
        buildingId: 'b1',
        unitId: 'un1',
        contractorId: 'sup2',
        description: "Rozetka ta'mirlash",
        estimatedCost: 320000,
        actualCost: 0,
        status: 'ASSIGNED',
        scheduledDate: '2025-06-06T14:00:00',
        completedAt: null,
        inspectionNotes: '',
        photos: [],
        createdAt: '2025-06-04T15:00:00',
        updatedAt: '2025-06-04T15:00:00',
      },
      {
        id: 'wo3',
        number: 'WO-2025-002',
        serviceRequestId: 'sr4',
        buildingId: 'b3',
        unitId: 'un4',
        contractorId: 'sup1',
        description: 'Konditsioner gaz zaryad',
        estimatedCost: 1200000,
        actualCost: 1100000,
        status: 'INSPECTION',
        scheduledDate: '2025-05-30T10:00:00',
        completedAt: null,
        inspectionNotes: '',
        photos: [],
        createdAt: '2025-05-28T10:00:00',
        updatedAt: '2025-05-30T16:00:00',
      },
      {
        id: 'wo4',
        number: 'WO-2025-001',
        serviceRequestId: '',
        buildingId: 'b1',
        unitId: null,
        contractorId: 'sup3',
        description: 'Lift texnik xizmat',
        estimatedCost: 2500000,
        actualCost: 2400000,
        status: 'COMPLETED',
        scheduledDate: '2025-05-15T09:00:00',
        completedAt: '2025-05-15T15:00:00',
        inspectionNotes: 'Hammasi OK',
        photos: [],
        createdAt: '2025-05-14T10:00:00',
        updatedAt: '2025-05-15T15:00:00',
      },
    ]

    materialRequests.value = [
      {
        id: 'mr1',
        workOrderId: 'wo1',
        items: [
          {
            id: 'mri1',
            warehouseItemId: 'wi1',
            name: 'Kran (mixer)',
            quantity: 1,
            unit: 'dona',
            unitPrice: 450000,
          },
          {
            id: 'mri2',
            warehouseItemId: 'wi3',
            name: 'Teflon lenta',
            quantity: 2,
            unit: 'rulon',
            unitPrice: 15000,
          },
        ],
        status: 'APPROVED',
        requestedBy: 'u1',
        approvedBy: 'u1',
        approvedAt: '2025-06-02T12:00:00',
        rejectedReason: null,
        createdAt: '2025-06-02T11:30:00',
      },
      {
        id: 'mr2',
        workOrderId: 'wo2',
        items: [
          {
            id: 'mri3',
            warehouseItemId: 'wi2',
            name: 'Rozetka (dubl)',
            quantity: 2,
            unit: 'dona',
            unitPrice: 35000,
          },
        ],
        status: 'PENDING',
        requestedBy: 'u1',
        approvedBy: null,
        approvedAt: null,
        rejectedReason: null,
        createdAt: '2025-06-04T15:30:00',
      },
      {
        id: 'mr3',
        workOrderId: 'wo3',
        items: [
          {
            id: 'mri4',
            warehouseItemId: 'wi4',
            name: 'Freon R-410A',
            quantity: 3,
            unit: 'kg',
            unitPrice: 180000,
          },
        ],
        status: 'PENDING',
        requestedBy: 'u1',
        approvedBy: null,
        approvedAt: null,
        rejectedReason: null,
        createdAt: '2025-05-28T11:00:00',
      },
    ]

    warehouseItems.value = [
      {
        id: 'wi1',
        sku: 'PLB-001',
        name: 'Kran (mixer)',
        category: 'Santexnika',
        unit: 'dona',
        stock: 15,
        minStock: 5,
        unitPrice: 450000,
        supplierId: 'sup1',
        createdAt: '2024-01-15',
      },
      {
        id: 'wi2',
        sku: 'ELC-002',
        name: 'Rozetka (dubl)',
        category: 'Elektr',
        unit: 'dona',
        stock: 48,
        minStock: 20,
        unitPrice: 35000,
        supplierId: 'sup2',
        createdAt: '2024-02-10',
      },
      {
        id: 'wi3',
        sku: 'PLB-003',
        name: 'Teflon lenta',
        category: 'Santexnika',
        unit: 'rulon',
        stock: 3,
        minStock: 10,
        unitPrice: 15000,
        supplierId: 'sup1',
        createdAt: '2024-03-20',
      },
      {
        id: 'wi4',
        sku: 'HVAC-004',
        name: 'Freon R-410A',
        category: 'HVAC',
        unit: 'kg',
        stock: 12,
        minStock: 5,
        unitPrice: 180000,
        supplierId: 'sup1',
        createdAt: '2024-04-05',
      },
      {
        id: 'wi5',
        sku: 'GEN-005',
        name: "Bo'yash (oq, 10L)",
        category: 'Umumiy',
        unit: 'banka',
        stock: 8,
        minStock: 3,
        unitPrice: 320000,
        supplierId: 'sup3',
        createdAt: '2024-05-12',
      },
      {
        id: 'wi6',
        sku: 'ELC-006',
        name: 'Kabel (3x2.5, 100m)',
        category: 'Elektr',
        unit: 'rulon',
        stock: 22,
        minStock: 5,
        unitPrice: 850000,
        supplierId: 'sup2',
        createdAt: '2024-06-01',
      },
    ]

    warehouseTransactions.value = [
      {
        id: 'wt1',
        itemId: 'wi1',
        type: 'IN',
        quantity: 20,
        unitPrice: 450000,
        reason: "Boshlang'ich zaxira",
        createdBy: 'u1',
        createdAt: '2024-01-15',
      },
      {
        id: 'wt2',
        itemId: 'wi1',
        type: 'OUT',
        quantity: 5,
        unitPrice: 450000,
        reason: 'WO-2025-003',
        createdBy: 'u1',
        createdAt: '2025-06-02',
      },
      {
        id: 'wt3',
        itemId: 'wi2',
        type: 'IN',
        quantity: 50,
        unitPrice: 35000,
        reason: 'Yetkazib berish',
        createdBy: 'u1',
        createdAt: '2025-03-01',
      },
      {
        id: 'wt4',
        itemId: 'wi3',
        type: 'OUT',
        quantity: 7,
        unitPrice: 15000,
        reason: 'WO-2025-001',
        createdBy: 'u1',
        createdAt: '2025-05-15',
      },
    ]

    suppliers.value = [
      {
        id: 'sup1',
        name: 'PlastServis MChJ',
        phone: '+998 71 123 45 67',
        email: 'info@plast.uz',
        address: 'Toshkent, Sergeli',
        contractUrl: 'contract-sup1.pdf',
        createdAt: '2024-01-10',
      },
      {
        id: 'sup2',
        name: 'ElektroHub MChJ',
        phone: '+998 71 234 56 78',
        email: 'sales@electrohub.uz',
        address: 'Toshkent, Yunusobod',
        contractUrl: null,
        createdAt: '2024-02-05',
      },
      {
        id: 'sup3',
        name: 'BuildSupply Plus',
        phone: '+998 71 345 67 89',
        email: 'info@buildsupply.uz',
        address: 'Toshkent, Chilonzor',
        contractUrl: 'contract-sup3.pdf',
        createdAt: '2024-03-15',
      },
    ]

    meters.value = [
      {
        id: 'm1',
        code: 'EL-B1-001',
        type: 'ELECTRICITY',
        serialNumber: 'EM-2024-001',
        buildingId: 'b1',
        unitId: 'un1',
        isActive: true,
        installedAt: '2024-06-01',
      },
      {
        id: 'm2',
        code: 'WT-B1-002',
        type: 'WATER',
        serialNumber: 'WM-2024-002',
        buildingId: 'b1',
        unitId: 'un1',
        isActive: true,
        installedAt: '2024-06-01',
      },
      {
        id: 'm3',
        code: 'EL-B2-003',
        type: 'ELECTRICITY',
        serialNumber: 'EM-2024-003',
        buildingId: 'b2',
        unitId: 'un2',
        isActive: true,
        installedAt: '2024-06-02',
      },
      {
        id: 'm4',
        code: 'GS-B3-004',
        type: 'GAS',
        serialNumber: 'GM-2024-004',
        buildingId: 'b3',
        unitId: null,
        isActive: true,
        installedAt: '2024-06-03',
      },
      {
        id: 'm5',
        code: 'HT-B4-005',
        type: 'HEAT',
        serialNumber: 'HM-2024-005',
        buildingId: 'b4',
        unitId: 'un3',
        isActive: false,
        installedAt: '2024-06-04',
      },
      {
        id: 'm6',
        code: 'EL-B1-006',
        type: 'ELECTRICITY',
        serialNumber: 'EM-2024-006',
        buildingId: 'b1',
        unitId: null,
        isActive: true,
        installedAt: '2024-06-05',
      },
    ]

    meterReadings.value = [
      {
        id: 'mr1',
        meterId: 'm1',
        readingAt: '2025-06-01T10:00:00',
        value: 15420,
        status: 'VERIFIED',
        photoUrl: 'reading-m1.jpg',
        submittedBy: 'u1',
        note: '',
        createdAt: '2025-06-01',
      },
      {
        id: 'mr2',
        meterId: 'm2',
        readingAt: '2025-06-01T10:15:00',
        value: 3420,
        status: 'VERIFIED',
        photoUrl: 'reading-m2.jpg',
        submittedBy: 'u1',
        note: '',
        createdAt: '2025-06-01',
      },
      {
        id: 'mr3',
        meterId: 'm3',
        readingAt: '2025-06-05T11:00:00',
        value: 8900,
        status: 'SUBMITTED',
        photoUrl: null,
        submittedBy: 'u1',
        note: 'Tekshiruv kerak',
        createdAt: '2025-06-05',
      },
    ]
  }

  const pendingMaterialApprovals = computed(() =>
    materialRequests.value.filter((mr) => mr.status === 'PENDING')
  )

  const lowStockItems = computed(() => warehouseItems.value.filter((i) => i.stock < i.minStock))

  return {
    serviceRequests,
    workOrders,
    materialRequests,
    warehouseItems,
    warehouseTransactions,
    suppliers,
    meters,
    meterReadings,
    initialized,
    pendingMaterialApprovals,
    lowStockItems,
    initMockData,
  }
})
